name: Flake Check!
on:
  pull_request:
  push:
    branches: [main]

jobs:
  nix-check:
    name: Check
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Run nix flake check
        run: nix flake check
